---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog/newyddion
  label: Newyddion
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/blog/erthyglau
  label: Erthyglau
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/blog/digwyddiadau
  label: Digwyddiadau
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/blog/dysgwyr
  label: Dysgwyr
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
